name: mlp_env
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.12.5
  - pip:
      - imbalanced-learn==0.13.0
      - jupyterlab==4.4.0
      - lightgbm==4.6.0
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - xgboost==3.0.0
